kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-resources-aro-strategies
data:
  blobstorage: |
    {"development": { "region": "", "createStrategy": {}, "deleteStrategy": {} }}
  redis: |
    {"development": { "region": "", "createStrategy": {}, "deleteStrategy": {}, "serviceUpdates": []  }}
  postgres: |
    {"development": { "region": "", "createStrategy": {}, "deleteStrategy": {}, "serviceUpdates": []  }}
  _network: |
    {"development": { "region": "", "createStrategy": {}, "deleteStrategy": {} }}

    
